# Generated by Django 4.2.23 on 2025-07-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerprofile',
            old_name='emergency_contact_name',
            new_name='emergency_name',
        ),
        migrations.RenameField(
            model_name='passengerprofile',
            old_name='emergency_contact_phone',
            new_name='emergency_phone',
        ),
    ]
