# Generated by Django 4.2.23 on 2025-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_emergency_contact_name_passengerprofile_emergency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
    ]
