# Generated by Django 4.2.23 on 2025-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='count_rating2',
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='driver_average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='driver_count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='passenger_average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='passenger_count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
