# Generated by Django 4.2.23 on 2025-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_driverprofile_count_rating2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('engaged', 'Engaged'), ('unavailable', 'Unavailable')], default='available', max_length=50),
        ),
    ]
