# Generated by Django 4.2.23 on 2025-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driverprofile_experience_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('engaged', 'Engaged'), ('unavailable', 'Unavailable')], default='available', max_length=50),
        ),
    ]
