# Generated by Django 4.2.23 on 2025-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_managerprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('engaged', 'Engaged'), ('unavailable', 'Unavailable')], default='available', max_length=50),
        ),
    ]
