# Generated by Django 4.2.23 on 2025-07-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
