# Generated by Django 4.2.23 on 2025-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
