# Generated by Django 5.2.5 on 2025-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_driverprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='count_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='count_rating',
            field=models.IntegerField(default=0),
        ),
    ]
