# Generated by Django 4.2.23 on 2025-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passengerprofile_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
