# Generated by Django 4.2.23 on 2025-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passengerprofile_count_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='rating_levels',
            field=models.JSONField(default=dict),
        ),
    ]
