# Generated by Django 4.2.23 on 2025-07-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passengerprofile_rating_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerprofile',
            name='rating_levels',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('manager', 'Manager')], default='passenger', max_length=20),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='users.profile')),
            ],
        ),
    ]
