# Generated by Django 4.2.23 on 2025-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_passengerprofile_rating_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='driver_average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='driver_count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='passenger_average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='passenger_count_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
