# Generated by Django 4.2.23 on 2025-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_driverprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
