# Generated by Django 4.2.23 on 2025-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_managerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
