# Generated by Django 4.2.23 on 2025-08-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_driverprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='driver_average_rating',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='driver_count_rating',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='passenger_average_rating',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='passenger_count_rating',
        ),
    ]
