# Generated by Django 4.2.23 on 2025-07-05 00:57

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('location_start', models.CharField(max_length=200)),
                ('location_end', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('travel_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trip_type', models.CharField(choices=[('Airport Transfers', 'Airport Transfers'), ('Special Events', 'Special Events'), ('Corporate Chauffeur', 'Corporate Chauffeur'), ('Private & VIP Chauffeur', 'Private & VIP Chauffeur')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in progress', 'In Progress'), ('cancelled', 'Cancelled'), ('modified', 'Modified'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('vehicle', models.CharField(choices=[('Rolls Royce Phantom', 'Rolls Royce Phantom'), ('Range Rover Vogue', 'Range Rover Vogue'), ('Mercedes Benz V-Class', 'Mercedes Benz V-Class'), ('Premium Limousine', 'Premium Limousine'), ('Classic Vintage Cars', 'Classic Vintage Cars')], default='Range Rover Vogue', max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_driver', to='users.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_passenger', to='users.passengerprofile')),
            ],
            options={
                'ordering': ['-travel_date'],
            },
        ),
    ]
