# Generated by Django 4.2.23 on 2025-07-03 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_start', models.CharField(max_length=200)),
                ('location_end', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trip_type', models.CharField(choices=[('Airport Transfers', 'Airport Transfers'), ('Special Events', 'Special Events'), ('Corporate Chauffeur', 'Corporate Chauffeur'), ('Private & VIP Chauffeur', 'Private & VIP Chauffeur')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('driver', models.CharField(choices=[('John Doe', 'John Doe'), ('Jane Smith', 'Jane Smith'), ('Michael Johnson', 'Michael Johnson'), ('Emily Davis', 'Emily Davis'), ('Chris Brown', 'Chris Brown')], max_length=50)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
