# Generated by Django 4.2.23 on 2025-07-04 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('location_start', models.CharField(max_length=200)),
                ('location_end', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('travel_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('trip_type', models.CharField(choices=[('Airport Transfers', 'Airport Transfers'), ('Special Events', 'Special Events'), ('Corporate Chauffeur', 'Corporate Chauffeur'), ('Private & VIP Chauffeur', 'Private & VIP Chauffeur')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('driver', models.CharField(choices=[('John Doe', 'John Doe'), ('Jane Smith', 'Jane Smith'), ('Michael Johnson', 'Michael Johnson'), ('Emily Davis', 'Emily Davis'), ('Chris Brown', 'Chris Brown')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('modified', 'Modified'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-travel_date'],
            },
        ),
    ]
