# Generated by Django 4.2.23 on 2025-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('modified', 'Modified'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
