# Generated by Django 4.2.23 on 2025-07-07 15:56

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.CharField(choices=[('Rolls Royce Phantom', 'Rolls Royce Phantom'), ('Range Rover Vogue', 'Range Rover Vogue'), ('Mercedes Benz V-Class', 'Mercedes Benz V-Class'), ('Premium Limousine', 'Premium Limousine'), ('Classic Vintage Cars', 'Classic Vintage Cars')], max_length=100),
        ),
    ]
