# Generated by Django 4.2.23 on 2025-07-17 10:27

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trip_driver_rating_trip_passenger_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_rating_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_rating_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
